"""new migration

Revision ID: 0a4234ac83eb
Revises: 4ad1fb34e9d4
Create Date: 2022-06-14 03:31:48.201398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a4234ac83eb'
down_revision = '4ad1fb34e9d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tips',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('content', sa.String(length=300), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('coops', sa.Column('next_feed_type', sa.String(length=100), nullable=True))
    op.add_column('coops', sa.Column('is_grown', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coops', 'is_grown')
    op.drop_column('coops', 'next_feed_type')
    op.drop_table('tips')
    # ### end Alembic commands ###
