"""tips migration

Revision ID: 7b1f82fe0fcf
Revises: 0a4234ac83eb
Create Date: 2022-06-14 04:40:41.979448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b1f82fe0fcf'
down_revision = '0a4234ac83eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tips', sa.Column('date_added', sa.DateTime(), nullable=True))
    op.add_column('tips', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'tips', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tips', type_='foreignkey')
    op.drop_column('tips', 'user_id')
    op.drop_column('tips', 'date_added')
    # ### end Alembic commands ###
