"""empty message

Revision ID: 82eefda869d2
Revises: d44c336b78d1
Create Date: 2022-06-13 08:51:20.815489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82eefda869d2'
down_revision = 'd44c336b78d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recipe', type_='foreignkey')
    op.drop_column('recipe', 'coop_id')
    op.alter_column('tips', 'title',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('tips', 'content',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tips', 'content',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    op.alter_column('tips', 'title',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.add_column('recipe', sa.Column('coop_id', sa.INTEGER(), nullable=False))
    op.create_foreign_key(None, 'recipe', 'coops', ['coop_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
